### Loading Data

In [166]:
import pandas as pd
import matplotlib.pyplot as plt

In [167]:
df = pd.read_csv("developer_ai_learning_raw.csv")

### Get Know The Data

In [168]:
df.sample(5)

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent
39349,39350,18-24 years old,1.0,Support engineer or analyst,"Yes, I am new to coding or currently a student",Books / Physical media;Videos (not associated ...,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,NaN,NaN,NaN
34839,34840,55-64 years old,43.0,"Developer, embedded applications or devices","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools weekly",Somewhat distrust,Favorable
49127,49128,25-34 years old,6.0,"Developer, full-stack","Yes, I am not new to coding but am learning ne...","School (i.e., University, College, etc)","Yes, I learned how to use AI-enabled tools for...","Other online resources (e.g. standard search, ...","Yes, I use AI tools weekly",Somewhat trust,Indifferent
18462,18463,35-44 years old,17.0,"Developer, front-end","Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,"Yes, I use AI tools weekly",Somewhat trust,Favorable
33310,33311,35-44 years old,25.0,Product manager,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,"Yes, I use AI tools daily",Somewhat trust,Very favorable

In [169]:
df.shape

(49191, 11)

In [170]:
df.columns

Index(['ResponseId', 'Age', 'YearsCode', 'DevType', 'LearnCodeChoose',
       'LearnCode', 'LearnCodeAI', 'AILearnHow', 'AISelect', 'AIAcc',
       'AISent'],
      dtype='str')

In [171]:
for col in df.columns:
    print(f"for col {col} - {len(df[col].unique())} unique values")

for col ResponseId - 49191 unique values
for col Age - 7 unique values
for col YearsCode - 79 unique values
for col DevType - 33 unique values
for col LearnCodeChoose - 4 unique values
for col LearnCode - 2768 unique values
for col LearnCodeAI - 6 unique values
for col AILearnHow - 1678 unique values
for col AISelect - 6 unique values
for col AIAcc - 6 unique values
for col AISent - 7 unique values

In [172]:
df.dtypes

ResponseId           int64
Age                    str
YearsCode          float64
DevType                str
LearnCodeChoose        str
LearnCode              str
LearnCodeAI            str
AILearnHow             str
AISelect               str
AIAcc                  str
AISent                 str
dtype: object

In [173]:
df.isna().sum()

ResponseId             0
Age                    0
YearsCode           6149
DevType             5511
LearnCodeChoose     2333
LearnCode          15635
LearnCodeAI         3990
AILearnHow         20934
AISelect           15471
AIAcc              15894
AISent             15724
dtype: int64

In [174]:
dim1 = df.shape[0]
for col in df.columns:
    print(f"For {col} : {df[col].isna().sum()}/{dim1} is null. ({df[col].isna().sum()/dim1*100:2f}%)")

For ResponseId : 0/49191 is null. (0.000000%)
For Age : 0/49191 is null. (0.000000%)
For YearsCode : 6149/49191 is null. (12.500254%)
For DevType : 5511/49191 is null. (11.203269%)
For LearnCodeChoose : 2333/49191 is null. (4.742737%)
For LearnCode : 15635/49191 is null. (31.784269%)
For LearnCodeAI : 3990/49191 is null. (8.111240%)
For AILearnHow : 20934/49191 is null. (42.556565%)
For AISelect : 15471/49191 is null. (31.450875%)
For AIAcc : 15894/49191 is null. (32.310789%)
For AISent : 15724/49191 is null. (31.965197%)

In [175]:
f"duplicated cols:{(df.duplicated().sum()/dim1 *100):2f}%"

'duplicated cols:0.000000%'

In [176]:
df[df.duplicated()]

Empty DataFrame
Columns: [ResponseId, Age, YearsCode, DevType, LearnCodeChoose, LearnCode, LearnCodeAI, AILearnHow, AISelect, AIAcc, AISent]
Index: []

In [177]:
df.AISent.unique()

<StringArray>
[     'Indifferent',        'Favorable',   'Very favorable',
      'Unfavorable',                nan, 'Very unfavorable',
           'Unsure']
Length: 7, dtype: str

In [178]:
as_l = df.LearnCode.str.split(";")
as_l[3]

['Other online resources (e.g. standard search, forum, online community)',
 'Videos (not associated with specific online course or certification)',
 'Stack Overflow or Stack Exchange',
 'Technical documentation (is generated for/by the tool or system)',
 'AI CodeGen tools or AI-enabled apps']

In [179]:
df[df.AILearnHow.str.contains(";")]

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent
2,3,35-44 years old,12.0,"Developer, front-end","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools daily",Somewhat trust,Favorable
3,4,35-44 years old,5.0,"Developer, back-end","Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,"Yes, I use AI tools weekly",Somewhat trust,Favorable
4,5,35-44 years old,22.0,Engineering manager,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,"Yes, I use AI tools weekly",Neither trust nor distrust,Favorable
5,6,45-54 years old,20.0,"Developer, back-end","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,"Yes, I use AI tools daily",Somewhat distrust,Indifferent
6,7,25-34 years old,13.0,"Developer, full-stack","Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,"Yes, I use AI tools daily",Somewhat trust,Favorable
...,...,...,...,...,...,...,...,...,...,...,...
49164,49165,25-34 years old,NaN,NaN,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,NaN,NaN,NaN
49168,49169,25-34 years old,6.0,"Developer, full-stack","Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,NaN,NaN
49175,49176,25-34 years old,11.0,AI/ML engineer,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools daily",Somewhat distrust,Favorable
49178,49179,45-54 years old,25.0,"Architect, software or solutions","No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,"Yes, I use AI tools weekly",Neither trust nor distrust,Indifferent
49188,49189,35-44 years old,31.0,"Architect, software or solutions","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,"Yes, I use AI tools monthly or infrequently",Neither trust nor distrust,Favorable

In [180]:
df.to_json("json-v1.json",orient="records", lines=True)


### Clear The Data

In [181]:
df.AILearnHow = df.AILearnHow.str.split(";")
df.LearnCode = df.LearnCode.str.split(";")

In [183]:
df.YearsCode.astype('Int64')

0          14
1          10
2          12
3           5
4          22
         ...
49186    <NA>
49187    <NA>
49188      31
49189    <NA>
49190       6
Name: YearsCode, Length: 49191, dtype: Int64

In [149]:
df.YearsCode = df.YearsCode.astype('Int64')

### Process Data

In [150]:
def label_experience_level(years:int):
    if years > 11:
        return "Highly Experienced"
    if years > 6:
        return "Experienced"
    if years > 3:
        return "Early Career"
    if years > 0:
        return "Beginner"
    return "Unknown"

In [151]:
df["experienceLevel"] = df.YearsCode.apply(label_experience_level)
df.sample()

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent,experienceLevel
728,729,45-54 years old,30,System administrator,"Yes, I am not new to coding but am learning ne...","[Other online resources (e.g. standard search,...","Yes, I learned how to use AI-enabled tools for...",[Technical documentation (is generated for/by ...,"Yes, I use AI tools monthly or infrequently",Highly distrust,Indifferent,Highly Experienced

In [152]:
df.LearnCode.explode().dropna().unique().tolist()

['Online Courses or Certification (includes all media types)',
 'Other online resources (e.g. standard search, forum, online community)',
 'Books / Physical media',
 'Videos (not associated with specific online course or certification)',
 'Stack Overflow or Stack Exchange',
 'Technical documentation (is generated for/by the tool or system)',
 'AI CodeGen tools or AI-enabled apps',
 'Colleague or on-the-job training',
 'Blogs or podcasts',
 'Coding Bootcamp',
 'Games or coding challenges',
 'School (i.e., University, College, etc)',
 'Other (please specify):']

In [153]:
def is_using_documentation(learn_code:list[str])-> bool:
    if not isinstance(learn_code, list):
        return False
    for learn_way in learn_code:
        if "Technical documentation" in learn_way:
            return True
    return False

def is_using_ai(learn_code:list[str]) -> bool:
    if not isinstance(learn_code, list):
        return False
    for learn_way in learn_code:
        if "AI CodeGen tools" in learn_way:
            return True
        if "AI-enabled apps" in learn_way:
            return True
    return False

def is_using_stack(learn_code:str)-> bool:
    if not isinstance(learn_code, list):
        return False
    for learn_way in learn_code:
        if "Stack Overflow" in learn_way:
            return True
    return False

In [154]:
df.LearnCode

0        [Online Courses or Certification (includes all...
1        [Online Courses or Certification (includes all...
2        [Online Courses or Certification (includes all...
3        [Other online resources (e.g. standard search,...
4                                                      NaN
                               ...
49186                                                  NaN
49187    [Online Courses or Certification (includes all...
49188    [Online Courses or Certification (includes all...
49189    [Videos (not associated with specific online c...
49190    [Online Courses or Certification (includes all...
Name: LearnCode, Length: 49191, dtype: object

In [155]:
df["usesDocumentation"] = df.LearnCode.apply(is_using_documentation)

In [156]:
df[df.ResponseId == 4889].LearnCode.tolist()

[['Books / Physical media',
  'Stack Overflow or Stack Exchange',
  'Technical documentation (is generated for/by the tool or system)']]

In [157]:
df["usesAIForLearning"] = df.LearnCode.apply(is_using_ai)

In [158]:
df[df.ResponseId == 27634].LearnCode.tolist()

[['Online Courses or Certification (includes all media types)',
  'Books / Physical media',
  'Stack Overflow or Stack Exchange',
  'Technical documentation (is generated for/by the tool or system)',
  'AI CodeGen tools or AI-enabled apps',
  'Blogs or podcasts']]

In [159]:
df["usesStackOverflow"] = df.LearnCode.apply(is_using_stack)

In [160]:
df[df.ResponseId == 2].LearnCode.tolist()

[['Online Courses or Certification (includes all media types)',
  'Other online resources (e.g. standard search, forum, online community)',
  'Books / Physical media',
  'Videos (not associated with specific online course or certification)',
  'Stack Overflow or Stack Exchange']]

In [161]:
df.to_json("json-v1.json",orient="records", lines=True)

In [162]:
df[df.YearsCode.isna() & (df.experienceLevel != "Unknown")]

Empty DataFrame
Columns: [ResponseId, Age, YearsCode, DevType, LearnCodeChoose, LearnCode, LearnCodeAI, AILearnHow, AISelect, AIAcc, AISent, experienceLevel, usesDocumentation, usesAIForLearning, usesStackOverflow]
Index: []

In [163]:
df

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent,experienceLevel,usesDocumentation,usesAIForLearning,usesStackOverflow
0,1,25-34 years old,14,"Developer, mobile","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...",[AI CodeGen tools or AI-enabled apps],"Yes, I use AI tools monthly or infrequently",Neither trust nor distrust,Indifferent,Highly Experienced,False,False,False
1,2,25-34 years old,10,"Developer, back-end","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...",[AI CodeGen tools or AI-enabled apps],"Yes, I use AI tools weekly",Neither trust nor distrust,Indifferent,Experienced,False,False,True
2,3,35-44 years old,12,"Developer, front-end","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...","[AI CodeGen tools or AI-enabled apps, Technica...","Yes, I use AI tools daily",Somewhat trust,Favorable,Highly Experienced,True,False,False
3,4,35-44 years old,5,"Developer, back-end","Yes, I am not new to coding but am learning ne...","[Other online resources (e.g. standard search,...","Yes, I learned how to use AI-enabled tools for...","[AI CodeGen tools or AI-enabled apps, Videos (...","Yes, I use AI tools weekly",Somewhat trust,Favorable,Early Career,True,True,True
4,5,35-44 years old,22,Engineering manager,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",[Technical documentation (is generated for/by ...,"Yes, I use AI tools weekly",Neither trust nor distrust,Favorable,Highly Experienced,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,18-24 years old,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,False,False,False
49187,49188,45-54 years old,<NA>,NaN,"Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,Unknown,False,False,False
49188,49189,35-44 years old,31,"Architect, software or solutions","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...","[AI CodeGen tools or AI-enabled apps, Videos (...","Yes, I use AI tools monthly or infrequently",Neither trust nor distrust,Favorable,Highly Experienced,True,True,True
49189,49190,25-34 years old,<NA>,NaN,"Yes, I am not new to coding but am learning ne...",[Videos (not associated with specific online c...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,Unknown,True,True,False
49190,49191,18-24 years old,6,Student,"Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...",[AI CodeGen tools or AI-enabled apps],NaN,NaN,NaN,Early Career,False,True,True

In [164]:
df_a = pd.DataFrame.from_records([{"a":1, "b":2}, {"a":10, "b":20}])
df_a.to_dict(orient="records")

[{'a': 1, 'b': 2}, {'a': 10, 'b': 20}]

In [165]:
df.YearsCode

0          14
1          10
2          12
3           5
4          22
         ...
49186    <NA>
49187    <NA>
49188      31
49189    <NA>
49190       6
Name: YearsCode, Length: 49191, dtype: Int64