### Loading Data

In [29]:
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv("developer_ai_learning_raw.csv")

### Get Know The Data

In [31]:
df.sample(5)

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent
12384,12385,35-44 years old,18.0,"Architect, software or solutions","Yes, I am not new to coding but am learning ne...","School (i.e., University, College, etc)","Yes, I learned how to use AI-enabled tools for...","Other online resources (e.g. standard search, ...","Yes, I use AI tools daily",Somewhat trust,Favorable
8350,8351,18-24 years old,4.0,"Developer, full-stack","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools daily",Somewhat trust,Very favorable
16250,16251,35-44 years old,22.0,"Senior executive (C-suite, VP, etc.)","No, I am not new to coding and did not learn n...",NaN,"No, I didn't spend time learning in the past year",NaN,"Yes, I use AI tools monthly or infrequently",Highly distrust,Unfavorable
28010,28011,25-34 years old,15.0,"Architect, software or solutions","No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,NaN,NaN,NaN
18242,18243,35-44 years old,20.0,Academic researcher,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools daily",Neither trust nor distrust,Favorable

In [32]:
df.shape

(49191, 11)

In [33]:
df.columns

Index(['ResponseId', 'Age', 'YearsCode', 'DevType', 'LearnCodeChoose',
       'LearnCode', 'LearnCodeAI', 'AILearnHow', 'AISelect', 'AIAcc',
       'AISent'],
      dtype='str')

In [34]:
for col in df.columns:
    print(f"for col {col} - {len(df[col].unique())} unique values")

for col ResponseId - 49191 unique values
for col Age - 7 unique values
for col YearsCode - 79 unique values
for col DevType - 33 unique values
for col LearnCodeChoose - 4 unique values
for col LearnCode - 2768 unique values
for col LearnCodeAI - 6 unique values
for col AILearnHow - 1678 unique values
for col AISelect - 6 unique values
for col AIAcc - 6 unique values
for col AISent - 7 unique values

In [35]:
df.dtypes

ResponseId           int64
Age                    str
YearsCode          float64
DevType                str
LearnCodeChoose        str
LearnCode              str
LearnCodeAI            str
AILearnHow             str
AISelect               str
AIAcc                  str
AISent                 str
dtype: object

In [36]:
df.isna().sum()

ResponseId             0
Age                    0
YearsCode           6149
DevType             5511
LearnCodeChoose     2333
LearnCode          15635
LearnCodeAI         3990
AILearnHow         20934
AISelect           15471
AIAcc              15894
AISent             15724
dtype: int64

In [37]:
dim1 = df.shape[0]
for col in df.columns:
    print(f"For {col} : {df[col].isna().sum()}/{dim1} is null. ({df[col].isna().sum()/dim1*100:2f}%)")

For ResponseId : 0/49191 is null. (0.000000%)
For Age : 0/49191 is null. (0.000000%)
For YearsCode : 6149/49191 is null. (12.500254%)
For DevType : 5511/49191 is null. (11.203269%)
For LearnCodeChoose : 2333/49191 is null. (4.742737%)
For LearnCode : 15635/49191 is null. (31.784269%)
For LearnCodeAI : 3990/49191 is null. (8.111240%)
For AILearnHow : 20934/49191 is null. (42.556565%)
For AISelect : 15471/49191 is null. (31.450875%)
For AIAcc : 15894/49191 is null. (32.310789%)
For AISent : 15724/49191 is null. (31.965197%)

In [49]:
f"duplicated cols:{(df.duplicated().sum()/dim1 *100):2f}%"

'duplicated cols:0.000000%'

In [39]:
df[df.duplicated()]

Empty DataFrame
Columns: [ResponseId, Age, YearsCode, DevType, LearnCodeChoose, LearnCode, LearnCodeAI, AILearnHow, AISelect, AIAcc, AISent]
Index: []

In [40]:
df.AISent.unique()

<StringArray>
[     'Indifferent',        'Favorable',   'Very favorable',
      'Unfavorable',                nan, 'Very unfavorable',
           'Unsure']
Length: 7, dtype: str