### Loading Data

In [37]:
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv("developer_ai_learning_raw.csv")

### Get Know The Data

In [39]:
df.sample(5)

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent
16102,16103,45-54 years old,22.0,DevOps engineer or professional,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,"No, and I don't plan to",Highly distrust,Unfavorable
23007,23008,25-34 years old,13.0,Data scientist,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,"Yes, I use AI tools daily",Somewhat distrust,Very favorable
24970,24971,25-34 years old,20.0,"Developer, mobile","Yes, I am not new to coding but am learning ne...",AI CodeGen tools or AI-enabled apps;Blogs or p...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN
27503,27504,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10854,10855,55-64 years old,45.0,"Developer, QA or test","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,"No, but I plan to soon",Highly distrust,Unsure

In [40]:
df.shape

(49191, 11)

In [41]:
df.columns

Index(['ResponseId', 'Age', 'YearsCode', 'DevType', 'LearnCodeChoose',
       'LearnCode', 'LearnCodeAI', 'AILearnHow', 'AISelect', 'AIAcc',
       'AISent'],
      dtype='str')

In [42]:
for col in df.columns:
    print(f"for col {col} - {len(df[col].unique())} unique values")

for col ResponseId - 49191 unique values
for col Age - 7 unique values
for col YearsCode - 79 unique values
for col DevType - 33 unique values
for col LearnCodeChoose - 4 unique values
for col LearnCode - 2768 unique values
for col LearnCodeAI - 6 unique values
for col AILearnHow - 1678 unique values
for col AISelect - 6 unique values
for col AIAcc - 6 unique values
for col AISent - 7 unique values

In [43]:
df.dtypes

ResponseId           int64
Age                    str
YearsCode          float64
DevType                str
LearnCodeChoose        str
LearnCode              str
LearnCodeAI            str
AILearnHow             str
AISelect               str
AIAcc                  str
AISent                 str
dtype: object

In [44]:
df.isna().sum()

ResponseId             0
Age                    0
YearsCode           6149
DevType             5511
LearnCodeChoose     2333
LearnCode          15635
LearnCodeAI         3990
AILearnHow         20934
AISelect           15471
AIAcc              15894
AISent             15724
dtype: int64

In [45]:
dim1 = df.shape[0]
for col in df.columns:
    print(f"For {col} : {df[col].isna().sum()}/{dim1} is null. ({df[col].isna().sum()/dim1*100:2f}%)")

For ResponseId : 0/49191 is null. (0.000000%)
For Age : 0/49191 is null. (0.000000%)
For YearsCode : 6149/49191 is null. (12.500254%)
For DevType : 5511/49191 is null. (11.203269%)
For LearnCodeChoose : 2333/49191 is null. (4.742737%)
For LearnCode : 15635/49191 is null. (31.784269%)
For LearnCodeAI : 3990/49191 is null. (8.111240%)
For AILearnHow : 20934/49191 is null. (42.556565%)
For AISelect : 15471/49191 is null. (31.450875%)
For AIAcc : 15894/49191 is null. (32.310789%)
For AISent : 15724/49191 is null. (31.965197%)

In [46]:
f"duplicated cols:{(df.duplicated().sum()/dim1 *100):2f}%"

'duplicated cols:0.000000%'

In [47]:
df[df.duplicated()]

Empty DataFrame
Columns: [ResponseId, Age, YearsCode, DevType, LearnCodeChoose, LearnCode, LearnCodeAI, AILearnHow, AISelect, AIAcc, AISent]
Index: []

In [48]:
df.AISent.unique()

<StringArray>
[     'Indifferent',        'Favorable',   'Very favorable',
      'Unfavorable',                nan, 'Very unfavorable',
           'Unsure']
Length: 7, dtype: str

In [49]:
as_l = df.LearnCode.str.split(";")
as_l[3]

['Other online resources (e.g. standard search, forum, online community)',
 'Videos (not associated with specific online course or certification)',
 'Stack Overflow or Stack Exchange',
 'Technical documentation (is generated for/by the tool or system)',
 'AI CodeGen tools or AI-enabled apps']

In [50]:
df[df.AILearnHow.str.contains(";")]

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent
2,3,35-44 years old,12.0,"Developer, front-end","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools daily",Somewhat trust,Favorable
3,4,35-44 years old,5.0,"Developer, back-end","Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,"Yes, I use AI tools weekly",Somewhat trust,Favorable
4,5,35-44 years old,22.0,Engineering manager,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,"Yes, I use AI tools weekly",Neither trust nor distrust,Favorable
5,6,45-54 years old,20.0,"Developer, back-end","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,"Yes, I use AI tools daily",Somewhat distrust,Indifferent
6,7,25-34 years old,13.0,"Developer, full-stack","Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,"Yes, I use AI tools daily",Somewhat trust,Favorable
...,...,...,...,...,...,...,...,...,...,...,...
49164,49165,25-34 years old,NaN,NaN,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,NaN,NaN,NaN
49168,49169,25-34 years old,6.0,"Developer, full-stack","Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,NaN,NaN
49175,49176,25-34 years old,11.0,AI/ML engineer,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,"Yes, I use AI tools daily",Somewhat distrust,Favorable
49178,49179,45-54 years old,25.0,"Architect, software or solutions","No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,"Yes, I use AI tools weekly",Neither trust nor distrust,Indifferent
49188,49189,35-44 years old,31.0,"Architect, software or solutions","Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,"Yes, I use AI tools monthly or infrequently",Neither trust nor distrust,Favorable

In [51]:
df.to_json("json-v1.json",orient="records", lines=True)


### Clear The Data

In [52]:
df.AILearnHow = df.AILearnHow.str.split(";")
df.LearnCode = df.LearnCode.str.split(";")

In [53]:
df.YearsCode.astype('Int64')

0          14
1          10
2          12
3           5
4          22
         ...
49186    <NA>
49187    <NA>
49188      31
49189    <NA>
49190       6
Name: YearsCode, Length: 49191, dtype: Int64

In [54]:
df.YearsCode = df.YearsCode.astype('Int64')

### Process Data

In [55]:
def label_experience_level(years:int):
    if years > 11:
        return "Highly Experienced"
    if years > 6:
        return "Experienced"
    if years > 3:
        return "Early Career"
    if years > 0:
        return "Beginner"
    return "Unknown"

In [56]:
df["experienceLevel"] = df.YearsCode.apply(label_experience_level)
df.sample()

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent,experienceLevel
5414,5415,25-34 years old,16,Engineering manager,"Yes, I am not new to coding but am learning ne...","[Other online resources (e.g. standard search,...","Yes, I learned how to use AI-enabled tools for...",[Technical documentation (is generated for/by ...,"Yes, I use AI tools daily",Somewhat distrust,Very favorable,Highly Experienced

In [57]:
df.LearnCode.explode().dropna().unique().tolist()

['Online Courses or Certification (includes all media types)',
 'Other online resources (e.g. standard search, forum, online community)',
 'Books / Physical media',
 'Videos (not associated with specific online course or certification)',
 'Stack Overflow or Stack Exchange',
 'Technical documentation (is generated for/by the tool or system)',
 'AI CodeGen tools or AI-enabled apps',
 'Colleague or on-the-job training',
 'Blogs or podcasts',
 'Coding Bootcamp',
 'Games or coding challenges',
 'School (i.e., University, College, etc)',
 'Other (please specify):']

In [58]:
def is_using_documentation(learn_code:list[str])-> bool:
    if not isinstance(learn_code, list):
        return False
    for learn_way in learn_code:
        if "Technical documentation" in learn_way:
            return True
    return False

def is_using_ai(learn_code:list[str]) -> bool:
    if not isinstance(learn_code, list):
        return False
    for learn_way in learn_code:
        if "AI CodeGen tools" in learn_way:
            return True
        if "AI-enabled apps" in learn_way:
            return True
    return False

def is_using_stack(learn_code:str)-> bool:
    if not isinstance(learn_code, list):
        return False
    for learn_way in learn_code:
        if "Stack Overflow" in learn_way:
            return True
    return False

In [59]:
df.LearnCode

0        [Online Courses or Certification (includes all...
1        [Online Courses or Certification (includes all...
2        [Online Courses or Certification (includes all...
3        [Other online resources (e.g. standard search,...
4                                                      NaN
                               ...
49186                                                  NaN
49187    [Online Courses or Certification (includes all...
49188    [Online Courses or Certification (includes all...
49189    [Videos (not associated with specific online c...
49190    [Online Courses or Certification (includes all...
Name: LearnCode, Length: 49191, dtype: object

In [60]:
df["usesDocumentation"] = df.LearnCode.apply(is_using_documentation)

In [61]:
df[df.ResponseId == 4889].LearnCode.tolist()

[['Books / Physical media',
  'Stack Overflow or Stack Exchange',
  'Technical documentation (is generated for/by the tool or system)']]

In [62]:
df["usesAIForLearning"] = df.LearnCode.apply(is_using_ai)

In [63]:
df[df.ResponseId == 27634].LearnCode.tolist()

[['Online Courses or Certification (includes all media types)',
  'Books / Physical media',
  'Stack Overflow or Stack Exchange',
  'Technical documentation (is generated for/by the tool or system)',
  'AI CodeGen tools or AI-enabled apps',
  'Blogs or podcasts']]

In [64]:
df["usesStackOverflow"] = df.LearnCode.apply(is_using_stack)

In [65]:
df[df.ResponseId == 2].LearnCode.tolist()

[['Online Courses or Certification (includes all media types)',
  'Other online resources (e.g. standard search, forum, online community)',
  'Books / Physical media',
  'Videos (not associated with specific online course or certification)',
  'Stack Overflow or Stack Exchange']]

In [66]:
df.to_json("json-v1.json",orient="records", lines=True)

In [67]:
df[df.YearsCode.isna() & (df.experienceLevel != "Unknown")]

Empty DataFrame
Columns: [ResponseId, Age, YearsCode, DevType, LearnCodeChoose, LearnCode, LearnCodeAI, AILearnHow, AISelect, AIAcc, AISent, experienceLevel, usesDocumentation, usesAIForLearning, usesStackOverflow]
Index: []

In [68]:
df

,ResponseId,Age,YearsCode,DevType,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,AISelect,AIAcc,AISent,experienceLevel,usesDocumentation,usesAIForLearning,usesStackOverflow
0,1,25-34 years old,14,"Developer, mobile","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...",[AI CodeGen tools or AI-enabled apps],"Yes, I use AI tools monthly or infrequently",Neither trust nor distrust,Indifferent,Highly Experienced,False,False,False
1,2,25-34 years old,10,"Developer, back-end","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...",[AI CodeGen tools or AI-enabled apps],"Yes, I use AI tools weekly",Neither trust nor distrust,Indifferent,Experienced,False,False,True
2,3,35-44 years old,12,"Developer, front-end","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...","[AI CodeGen tools or AI-enabled apps, Technica...","Yes, I use AI tools daily",Somewhat trust,Favorable,Highly Experienced,True,False,False
3,4,35-44 years old,5,"Developer, back-end","Yes, I am not new to coding but am learning ne...","[Other online resources (e.g. standard search,...","Yes, I learned how to use AI-enabled tools for...","[AI CodeGen tools or AI-enabled apps, Videos (...","Yes, I use AI tools weekly",Somewhat trust,Favorable,Early Career,True,True,True
4,5,35-44 years old,22,Engineering manager,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",[Technical documentation (is generated for/by ...,"Yes, I use AI tools weekly",Neither trust nor distrust,Favorable,Highly Experienced,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,18-24 years old,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,False,False,False
49187,49188,45-54 years old,<NA>,NaN,"Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,Unknown,False,False,False
49188,49189,35-44 years old,31,"Architect, software or solutions","Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...","[AI CodeGen tools or AI-enabled apps, Videos (...","Yes, I use AI tools monthly or infrequently",Neither trust nor distrust,Favorable,Highly Experienced,True,True,True
49189,49190,25-34 years old,<NA>,NaN,"Yes, I am not new to coding but am learning ne...",[Videos (not associated with specific online c...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,Unknown,True,True,False
49190,49191,18-24 years old,6,Student,"Yes, I am not new to coding but am learning ne...",[Online Courses or Certification (includes all...,"Yes, I learned how to use AI-enabled tools for...",[AI CodeGen tools or AI-enabled apps],NaN,NaN,NaN,Early Career,False,True,True

In [69]:
df_a = pd.DataFrame.from_records([{"a":1, "b":2}, {"a":10, "b":20}])
df_a.to_dict(orient="records")

[{'a': 1, 'b': 2}, {'a': 10, 'b': 20}]

In [70]:
df.YearsCode

0          14
1          10
2          12
3           5
4          22
         ...
49186    <NA>
49187    <NA>
49188      31
49189    <NA>
49190       6
Name: YearsCode, Length: 49191, dtype: Int64

In [71]:
df.dtypes

ResponseId            int64
Age                     str
YearsCode             Int64
DevType                 str
LearnCodeChoose         str
LearnCode            object
LearnCodeAI             str
AILearnHow           object
AISelect                str
AIAcc                   str
AISent                  str
experienceLevel         str
usesDocumentation      bool
usesAIForLearning      bool
usesStackOverflow      bool
dtype: object

In [ ]:
d = df.to_dict(orient='records')

[{'ResponseId': 1,
  'Age': '25-34 years old',
  'YearsCode': 14,
  'DevType': 'Developer, mobile',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'Other online resources (e.g. standard search, forum, online community)'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps'],
  'AISelect': 'Yes, I use AI tools monthly or infrequently',
  'AIAcc': 'Neither trust nor distrust',
  'AISent': 'Indifferent',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 2,
  'Age': '25-34 years old',
  'YearsCode': 10,
  'DevType': 'Developer, back-end',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'Other online resources (e.g. standard search, forum, online community)',
   'Books / Physical media',
   'Videos (not associated with specific online course or certification)',
   'Stack Overflow or Stack Exchange'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps'],
  'AISelect': 'Yes, I use AI tools weekly',
  'AIAcc': 'Neither trust nor distrust',
  'AISent': 'Indifferent',
  'experienceLevel': 'Experienced',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': True},
 {'ResponseId': 3,
  'Age': '35-44 years old',
  'YearsCode': 12,
  'DevType': 'Developer, front-end',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'Videos (not associated with specific online course or certification)',
   'Technical documentation (is generated for/by the tool or system)'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps',
   'Technical documentation (is generated for/by the tool or system)',
   'Videos (not associated with specific online course or certification)'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Somewhat trust',
  'AISent': 'Favorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 4,
  'Age': '35-44 years old',
  'YearsCode': 5,
  'DevType': 'Developer, back-end',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Other online resources (e.g. standard search, forum, online community)',
   'Videos (not associated with specific online course or certification)',
   'Stack Overflow or Stack Exchange',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps',
   'Videos (not associated with specific online course or certification)',
   'Other online resources (e.g. standard search, forum, online community)'],
  'AISelect': 'Yes, I use AI tools weekly',
  'AIAcc': 'Somewhat trust',
  'AISent': 'Favorable',
  'experienceLevel': 'Early Career',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': True},
 {'ResponseId': 5,
  'Age': '35-44 years old',
  'YearsCode': 22,
  'DevType': 'Engineering manager',
  'LearnCodeChoose': 'No, I am not new to coding and did not learn new coding techniques or programming languages',
  'LearnCode': nan,
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['Technical documentation (is generated for/by the tool or system)',
   'Other online resources (e.g. standard search, forum, online community)'],
  'AISelect': 'Yes, I use AI tools weekly',
  'AIAcc': 'Neither trust nor distrust',
  'AISent': 'Favorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 6,
  'Age': '45-54 years old',
  'YearsCode': 20,
  'DevType': 'Developer, back-end',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'Other online resources (e.g. standard search, forum, online community)',
   'Books / Physical media',
   'Videos (not associated with specific online course or certification)',
   'Stack Overflow or Stack Exchange',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps',
   'Colleague or on-the-job training',
   'Blogs or podcasts'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools required for my job or to benefit my career',
  'AILearnHow': ['Technical documentation (is generated for/by the tool or system)',
   'Videos (not associated with specific online course or certification)',
   'Other online resources (e.g. standard search, forum, online community)',
   'Colleague or on-the-job training',
   'Online Courses or Certification (includes all media types)',
   'Blogs or podcasts'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Somewhat distrust',
  'AISent': 'Indifferent',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': True},
 {'ResponseId': 7,
  'Age': '25-34 years old',
  'YearsCode': 13,
  'DevType': 'Developer, full-stack',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Videos (not associated with specific online course or certification)',
   'AI CodeGen tools or AI-enabled apps',
   'Blogs or podcasts'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps',
   'Videos (not associated with specific online course or certification)',
   'Other online resources (e.g. standard search, forum, online community)',
   'Blogs or podcasts'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Somewhat trust',
  'AISent': 'Favorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': False,
  'usesAIForLearning': True,
  'usesStackOverflow': False},
 {'ResponseId': 8,
  'Age': '35-44 years old',
  'YearsCode': 30,
  'DevType': 'Architect, software or solutions',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Books / Physical media',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps',
   'Blogs or podcasts'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps', 'Blogs or podcasts'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Somewhat trust',
  'AISent': 'Very favorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': False},
 {'ResponseId': 9,
  'Age': '25-34 years old',
  'YearsCode': 15,
  'DevType': 'Data engineer',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'Other online resources (e.g. standard search, forum, online community)',
   'Books / Physical media',
   'Videos (not associated with specific online course or certification)',
   'Stack Overflow or Stack Exchange',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps',
   'Blogs or podcasts'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['Technical documentation (is generated for/by the tool or system)',
   'Videos (not associated with specific online course or certification)',
   'Other online resources (e.g. standard search, forum, online community)',
   'Blogs or podcasts'],
  'AISelect': 'Yes, I use AI tools monthly or infrequently',
  'AIAcc': 'Neither trust nor distrust',
  'AISent': 'Indifferent',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': True},
 {'ResponseId': 10,
  'Age': '25-34 years old',
  'YearsCode': 10,
  'DevType': 'Developer, mobile',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Other online resources (e.g. standard search, forum, online community)',
   'Books / Physical media',
   'Videos (not associated with specific online course or certification)',
   'Stack Overflow or Stack Exchange',
   'Technical documentation (is generated for/by the tool or system)',
   'Blogs or podcasts'],
  'LearnCodeAI': 'No, I learned something that was not related to AI or AI enablement for my personal curiosity and/or hobbies',
  'AILearnHow': nan,
  'AISelect': "No, and I don't plan to",
  'AIAcc': 'Highly distrust',
  'AISent': 'Unfavorable',
  'experienceLevel': 'Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': False,
  'usesStackOverflow': True},
 {'ResponseId': 11,
  'Age': '25-34 years old',
  'YearsCode': 9,
  'DevType': 'Developer, back-end',
  'LearnCodeChoose': 'No, I am not new to coding and did not learn new coding techniques or programming languages',
  'LearnCode': nan,
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps',
   'Technical documentation (is generated for/by the tool or system)',
   'Videos (not associated with specific online course or certification)',
   'Colleague or on-the-job training',
   'Blogs or podcasts'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Somewhat distrust',
  'AISent': 'Very favorable',
  'experienceLevel': 'Experienced',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 12,
  'Age': '18-24 years old',
  'YearsCode': 5,
  'DevType': 'Developer, back-end',
  'LearnCodeChoose': 'No, I am not new to coding and did not learn new coding techniques or programming languages',
  'LearnCode': nan,
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['Videos (not associated with specific online course or certification)',
   'Other online resources (e.g. standard search, forum, online community)'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Neither trust nor distrust',
  'AISent': 'Very favorable',
  'experienceLevel': 'Early Career',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 13,
  'Age': '35-44 years old',
  'YearsCode': 10,
  'DevType': 'Developer, front-end',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Videos (not associated with specific online course or certification)',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps'],
  'LearnCodeAI': 'No, I learned something that was not related to AI or AI enablement as required for my job or to benefit my career',
  'AILearnHow': nan,
  'AISelect': 'Yes, I use AI tools monthly or infrequently',
  'AIAcc': 'Somewhat distrust',
  'AISent': 'Unfavorable',
  'experienceLevel': 'Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': False},
 {'ResponseId': 14,
  'Age': '25-34 years old',
  'YearsCode': 6,
  'DevType': 'Developer, full-stack',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools required for my job or to benefit my career',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps',
   'Other online resources (e.g. standard search, forum, online community)',
   'Colleague or on-the-job training',
   'Online Courses or Certification (includes all media types)'],
  'AISelect': nan,
  'AIAcc': nan,
  'AISent': nan,
  'experienceLevel': 'Early Career',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': False},
 {'ResponseId': 15,
  'Age': '35-44 years old',
  'YearsCode': None,
  'DevType': 'Architect, software or solutions',
  'LearnCodeChoose': 'No, I am not new to coding and did not learn new coding techniques or programming languages',
  'LearnCode': nan,
  'LearnCodeAI': 'No, I learned something that was not related to AI or AI enablement for my personal curiosity and/or hobbies',
  'AILearnHow': nan,
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Somewhat trust',
  'AISent': 'Favorable',
  'experienceLevel': 'Unknown',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 16,
  'Age': '18-24 years old',
  'YearsCode': 3,
  'DevType': 'Developer, mobile',
  'LearnCodeChoose': 'Yes, I am new to coding or currently a student',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'AI CodeGen tools or AI-enabled apps',
   'Colleague or on-the-job training',
   'Blogs or podcasts',
   'Coding Bootcamp'],
  'LearnCodeAI': 'No, I learned something that was not related to AI or AI enablement as required for my job or to benefit my career',
  'AILearnHow': nan,
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Highly trust',
  'AISent': 'Favorable',
  'experienceLevel': 'Beginner',
  'usesDocumentation': False,
  'usesAIForLearning': True,
  'usesStackOverflow': False},
 {'ResponseId': 17,
  'Age': '65 years or older',
  'YearsCode': 40,
  'DevType': 'Financial analyst or engineer',
  'LearnCodeChoose': 'No, I am not new to coding and did not learn new coding techniques or programming languages',
  'LearnCode': nan,
  'LearnCodeAI': "No, I didn't spend time learning in the past year",
  'AILearnHow': nan,
  'AISelect': "No, and I don't plan to",
  'AIAcc': 'Highly distrust',
  'AISent': 'Very unfavorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 18,
  'Age': '25-34 years old',
  'YearsCode': 8,
  'DevType': 'Developer, full-stack',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Online Courses or Certification (includes all media types)',
   'Books / Physical media',
   'Videos (not associated with specific online course or certification)',
   'Stack Overflow or Stack Exchange',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps',
   'Blogs or podcasts'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['Videos (not associated with specific online course or certification)',
   'Other online resources (e.g. standard search, forum, online community)',
   'Stack Overflow or Stack Exchange'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Neither trust nor distrust',
  'AISent': 'Unfavorable',
  'experienceLevel': 'Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': True},
 {'ResponseId': 19,
  'Age': '35-44 years old',
  'YearsCode': 20,
  'DevType': 'Developer, back-end',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Stack Overflow or Stack Exchange',
   'Technical documentation (is generated for/by the tool or system)',
   'AI CodeGen tools or AI-enabled apps',
   'Blogs or podcasts'],
  'LearnCodeAI': "No, I didn't spend time learning in the past year",
  'AILearnHow': nan,
  'AISelect': "No, and I don't plan to",
  'AIAcc': 'Highly distrust',
  'AISent': 'Very unfavorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': True,
  'usesStackOverflow': True},
 {'ResponseId': 20,
  'Age': '25-34 years old',
  'YearsCode': 6,
  'DevType': 'Academic researcher',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Videos (not associated with specific online course or certification)',
   'AI CodeGen tools or AI-enabled apps'],
  'LearnCodeAI': 'Yes, I learned how to use AI-enabled tools for my personal curiosity and/or hobbies',
  'AILearnHow': ['AI CodeGen tools or AI-enabled apps',
   'Videos (not associated with specific online course or certification)'],
  'AISelect': 'Yes, I use AI tools daily',
  'AIAcc': 'Neither trust nor distrust',
  'AISent': 'Very favorable',
  'experienceLevel': 'Early Career',
  'usesDocumentation': False,
  'usesAIForLearning': True,
  'usesStackOverflow': False},
 {'ResponseId': 21,
  'Age': '55-64 years old',
  'YearsCode': 45,
  'DevType': 'Academic researcher',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Other online resources (e.g. standard search, forum, online community)',
   'Stack Overflow or Stack Exchange'],
  'LearnCodeAI': 'No, I learned something that was not related to AI or AI enablement for my personal curiosity and/or hobbies',
  'AILearnHow': nan,
  'AISelect': "No, and I don't plan to",
  'AIAcc': 'Highly distrust',
  'AISent': 'Unfavorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': False,
  'usesAIForLearning': False,
  'usesStackOverflow': True},
 {'ResponseId': 22,
  'Age': '45-54 years old',
  'YearsCode': 35,
  'DevType': 'Academic researcher',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Other online resources (e.g. standard search, forum, online community)',
   'Books / Physical media',
   'Videos (not associated with specific online course or certification)',
   'Technical documentation (is generated for/by the tool or system)',
   'Games or coding challenges'],
  'LearnCodeAI': "No, I didn't spend time learning in the past year",
  'AILearnHow': nan,
  'AISelect': "No, and I don't plan to",
  'AIAcc': 'Highly distrust',
  'AISent': 'Very unfavorable',
  'experienceLevel': 'Highly Experienced',
  'usesDocumentation': True,
  'usesAIForLearning': False,
  'usesStackOverflow': False},
 {'ResponseId': 23,
  'Age': '25-34 years old',
  'YearsCode': 11,
  'DevType': 'Developer, full-stack',
  'LearnCodeChoose': 'Yes, I am not new to coding but am learning new coding techniques or programming language',
  'LearnCode': ['Other online resources (e.g. standard search, forum, online community)',
   'Videos (not associated with specific online course or certification)',
   'Stack Overflow or Stack Exchange',
   'Technical documentation (is generated for/by the tool or system)',
   'Games or coding challenges'],

In [75]:
pd.DataFrame.from_records(d).dtypes

ResponseId             int64
Age                      str
YearsCode            float64
DevType                  str
LearnCodeChoose          str
LearnCode             object
LearnCodeAI              str
AILearnHow            object
AISelect                 str
AIAcc                    str
AISent                   str
experienceLevel          str
usesDocumentation       bool
usesAIForLearning       bool
usesStackOverflow       bool
dtype: object

In [86]:
df.to_csv("a.csv")

In [87]:
import csv
with open("a.csv") as f:
    r = csv.DictReader(f)
    l = []
    for i in r:
        l.append(i)

In [88]:
new = pd.DataFrame.from_records(l)

In [89]:
new.dtypes

                     str
ResponseId           str
Age                  str
YearsCode            str
DevType              str
LearnCodeChoose      str
LearnCode            str
LearnCodeAI          str
AILearnHow           str
AISelect             str
AIAcc                str
AISent               str
experienceLevel      str
usesDocumentation    str
usesAIForLearning    str
usesStackOverflow    str
dtype: object

In [84]:
pd.to_numeric(new.ResponseId)

0            1
1            2
2            3
3            4
4            5
         ...
49186    49187
49187    49188
49188    49189
49189    49190
49190    49191
Name: ResponseId, Length: 49191, dtype: int64